### ISSUE TITLE
Code should figure out strain expression data sheets  and deleted gene based on name, not order

### ISSUE THREAD

**Issue by juansc** [kdahlquist/GRNmap#52] opened 2015-03-06 00:12 UTC
The code should also be able to figure out the deleted strain based on just the  name. Ideally, we only provide the names of the strains but we don't specify the number of the sheet or which gene was deleted in the strain.

**Comment by kdahlquist** [comment] 2015-05-25 18:32
I changed the name of this issue to be more specific.

I think I want to clarify the statement of the problem.  There are two parts to this:  

1.  We want the code to figure out which expression data belongs to which strain, based on the name of the strain, not the order of the worksheet in the workbook.  Currently, in the optimization_parameters worksheet, the user specifies the order of the worksheet.

2.  We want the code to figure out which gene is deleted by the name of the gene, not the order in which it appears in the list of genes. Currently, in the optimization_parameters worksheet, the user specifies the order of the gene in the list of genes.

**Comment by kdahlquist** [comment] 2015-05-27 23:00
Moving this up to a 0.5 priority because it is a natural follow-on to the changes we are making to the sheet names.

**Comment by juansc** [comment] 2015-09-18 02:29
The code already satisfies the first of the two:

1. We want the code to figure out which expression data belongs to which strain, based on the name of the strain, not the order of the worksheet in the workbook. Currently, in the optimization_parameters worksheet, the user specifies the order of the worksheet.

**Comment by kdahlquist** [comment] 2015-09-21 05:08
See my note about test-driven development on issue #129 . If you haven't already, write the test *before* doing any coding, fail the test, then fix the code to pass the test.

**Comment by dondi** [comment] 2015-09-21 13:55
In the earlier comment about the code already satisfying condition 1, can the unit tests for that be identified? If they exist, were they written before the behavior was implemented? If the answer to either these is “no,” then that was not TDD-compliant. Stick to the discipline of TDD. Watch more Uncle Bob videos if you need inspiration. @trixr4kdz has already figured out the framework in MATLAB so adding tests would be incremental to that framework, not anything wildly new.

**Comment by juansc** [comment] 2015-09-23 23:05
As of now the beta code does not need the Sheet row. I implemented the code to allow GRNmap to detect which gene gets deleted based on the name. However, the values in the output sheet differ in the fourth and fifth decimal place. While we don't typically care about that level of accuracy, I am not sure whether this is an indication that something else is going on.

**Comment by kdahlquist** [comment] 2015-09-24 17:13
Just to add another note from the meeting.  @tessaam said that when we compared runs with two input files that were identical except for being .xls and .xlsx, the maximum difference that we saw was in the 6th decimal place.  So, empirically that is our benchmark for the amount of difference we will tolerate.

**Comment by juansc** [comment] 2015-10-21 23:11
The code is now capable of finding the right row to delete.

**Comment by kdahlquist** [comment] 2016-01-19 00:52
The last comment by @juansc says that the code is now capable of finding the right row to delete.  Can you say a bit more about how this works.  I've referenced it in issue #119.

**Comment by kdahlquist** [comment] 2016-01-20 18:59
This is how the code should work:

It will figure out what genes are deleted from the "Strain" parameter.  It ignores the "wt" strain.  For the other strains, it strips off the initial "d" and reads the gene names from the deletion strains.  It then looks through the other sheets to find that gene name.  It should be case insensitive.

@kdahlquist tried an input sheet with the "Deletion" parameter and got an error.  She will reproduce this bug and report it more fully.

No unit tests have been created for this, yet and need to be done asap:
* need to test functionality
* need to test case sensitivity, one spreadsheet will be all lower case, one will be all upper case, and one will be mixed case
* need to test for trailing spaces

**Comment by juansc** [comment] 2016-01-24 00:44
I added tests which verify the following:
* The correct strain is identified regardless of the case
* The Deletion parameter is not needed

I will now work on trailing spaces and making sure that the Deletion paramter, if included, is ignored.

**Comment by juansc** [comment] 2016-01-24 01:07
I added a test in  1beeade0028557ab272c30a3fa06763f93d441d7 that verifies that including the Deletion parameter will not affect the functionality.

**Comment by juansc** [comment] 2016-01-24 03:16
I added a test in  48abf7eb2c9b5c71ea1bdc2eae560897e58a2a46 where GRNmap ignores leading or trailing whitespaces in gene names when deleting strain.

**Comment by kdahlquist** [comment] 2016-01-27 00:47
I have verified with one input worksheet that the "Deletion" parameter is not needed and the strains were detected.  We will run the tests at our meeting tomorrow before closing this.

**Comment by kdahlquist** [comment] 2016-01-27 19:10
We ran the test suite in the meeting and are closing this now.

**Closed by kdahlquist** 2016-01-27 19:10 UTC
Labels: documentation, functionality, priority 0, review requested
