### ISSUE TITLE
Append successive numbers to figure names when running the L-curve

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#183] opened 2016-02-14 00:50 UTC
@kdahlquist said in issue #174:

I think we should adhere to what we have designed into the program:
* if make_graphs = 0, no expression graphs made or saved (but the optimization diagnostic is always saved)
* if make_graphs = 1, all expression graphs made and saved.  

The way @bengfitzpatrick is saving the output .xlsx workbooks is by appending an underscore followed by a number to the end of the file name, e.g., "_1", "_2", etc. which corresponds to the order of the runs.  It seems that if make_graphs = 1, then we could save the files with the gene name and _1, _2, etc.  Then the user decides whether they want to make and save all the graphs or not.

after the jpegs are saved for each run, close the Matlab figure windows for the run.

**Comment by trixr4kdz** [comment] 2016-02-17 06:51
A test has been created for this functionality and the issue of appending numbers to figures has been implemented.

**Comment by kdahlquist** [comment] 2016-02-17 18:25
Let's discuss this in relation to the open issues #135 and #144, because they might be fixed now.

**Comment by kdahlquist** [comment] 2016-02-18 22:12
As noted in the meeting, this is a little different than #135 and #144.

I have confirmed that this now works with the file: dHAP4_15_gene_network_deletion_added_input_KD_20160126.xlsx with the optimization parameters:

L_curve	=1
estimate_params	=1
make_graphs	=1
fix_P	=1
fix_b=1

**Closed by kdahlquist** 2016-02-18 22:12 UTC
Labels: functionality, priority 0, review requested
