### ISSUE TITLE
merge L curve and beta branch

### ISSUE THREAD

**Issue by bengfitzpatrick** [kdahlquist/GRNmap#148] opened 2015-10-21 22:53 UTC
Compare each m-file for functionality and bug fixes.

**Comment by trixr4kdz** [comment] 2015-10-28 06:16
Merged L-curve into beta. However, when running the tests, it would seem that the actual output are off by a decimal place from what was expected. These are most prominent when testing the optimization diagnostics (e.g., if expected output is 4.5678, then actual output is 0.4567; this seems to be the case for all values in optimization diagnostics sheet). Also, although small differences are expected since @bengfitzpatrick was working on master branch, most of the calculated values are now off by about 1e-05 from the test files.

**Comment by trixr4kdz** [comment] 2015-10-28 06:34
Also, where exactly would we want the *.mat file to be written? Right now, the overall *.mat files are saved just outside of the folder where the input sheet is located.

**Comment by bengfitzpatrick** [comment] 2015-10-28 17:09
trixie, i would like you to take a look at the code to see where this difference might arise.  The L-Curve branch included not only the L-curve driver routine but also a number of bug fixes.  Doing some code diffs between the two branches might illuminate the discrepancies. I'm reassigning this back to you ;-)

**Comment by juansc** [comment] 2015-10-28 22:59
Notes from the meeting: In the future, when reporting errors or problems for other people, we should report how to reproduce the error. We should report the version of the code, i.e. the branch, the commit, the input sheet, and all necessary information to recreate the bug. We should also be able to document the errors more precisely by stating the values that have changed, how they changed so that we can reproduce the errors and allows us to get more helpful feedback.

**Comment by juansc** [comment] 2015-11-11 17:47
After reviewing the code and looking for obvious bugs and cleaning up the code, I have decided to branch off of beta and make a new branch where we can debug the code. I am compiling a list of errors so we can check all the files that fail and debug them.

**Comment by juansc** [comment] 2015-11-11 18:18
Most of these tests fail because there is a relative error with an order of magnitude somewhere between 10^-6 to 10^-3. The sheet that is always of by a factor of 10 or 100 is the optimization diagnostic sheet. NONE of the sheets pass the optimization diagnostic test.

**Comment by trixr4kdz** [comment] 2015-11-11 22:47
The previous code, before the merge, contained this code:

``` matlab
    for iT = 1:length(expression_timepoints)
        for iF =  1:length(log2FC(qq).t(iT).indx)
            errormat = errormat+((log2(x1(iT,:)))'-d(:,log2FC(qq).t(iT).indx(iF))).^2;
        end
    end
    
    SSE(:,qq) = errormat;
```

After the merge, the only difference in calculations is that the SSE is being divided by the nSE in the following snippet:
``` matlab
    nSE = 0;
    errMatStrain = 0;
    for iT = 1:length(expression_timepoints)    
        for iF =  1:length(log2FC(qq).t(iT).indx)
            errMatStrain = errMatStrain+((log2(x1(iT,:)))'-d(:,log2FC(qq).t(iT).indx(iF))).^2;
            nSE      = nSE + 1;
        end
    end
    errormat = errormat + errMatStrain;
    
    
    SSE(:,qq) = errormat/nSE;
```

**Comment by kdahlquist** [comment] 2016-01-20 19:28
This is complete as of the closure of #164.  The bug reported above has been opened as a new issue #165

**Closed by kdahlquist** 2016-01-20 19:28 UTC
Labels: functionality, priority 0.5, question
