### ISSUE TITLE
Undefined function or variable 'simulation_timepoints' -- error in beta

### ISSUE THREAD

**Issue by bengfitzpatrick** [kdahlquist/GRNmap#131] opened 2015-09-23 16:03 UTC
In developing the L Curve code, I had to use the current master branch.  The beta branch (downloaded 8pm PDT 2015 Sep 22) fails with the error

Undefined function or variable 'simulation_timepoints'.

Error in readInputSheet (line 84)
GRNstruct.controlParams.simulation_timepoints        = simulation_timepoints;

Error in GRNmodel (line 30)
GRNstruct = readInputSheet(GRNstruct);

------
I'm assuming this is a naming transition that is incomplete.

**Comment by trixr4kdz** [comment] 2015-09-23 20:07
Per the meeting from last week, the new naming convention was implemented so the variable names in the optimization parameters worksheet would have to be changed (i.e. simtime would be called simulation_timepoints). However, I've decided to move my previous changes into a different branch and will work on that one separately from beta.

**Comment by kdahlquist** [comment] 2015-10-14 21:55
I think we can close this.  We'll open another issue about merging the L-curve and beta branches and dealing with the changes caused by renaming the variables.

**Closed by kdahlquist** 2015-10-14 21:55 UTC
Labels: bug, functionality, priority 0
