### ISSUE TITLE
Thresholds and Production Rates being outputted

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#68] opened 2015-05-02 02:00 UTC
Make sure that the estimated production rates and thresholds are being outputted correctly. That is, if fix_b = 0, output thresholds, and if fix_P = 0, output production rates.

**Comment by kdahlquist** [comment] 2015-05-27 22:26
closing this as a duplicate of other reported issues.

**Closed by kdahlquist** 2015-05-27 22:26 UTC
Labels: bug, duplicate, functionality
